version: "3.7"
services:
  mariadb:
    container_name: jeedom-db
    restart: always
    image: "mariadb:latest"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    volumes:
      - ./mysql:/var/lib/mysql
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.entryPoints=mysql"
      - "traefik.tcp.services.mysql-svc.loadbalancer.server.port=3306"
      - "traefik.tcp.routers.mysql.service=mysql-svc"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.routers.mosquitto.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mosquitto.entryPoints=mosquitto"
      - "traefik.tcp.services.mosquitto-svc.loadbalancer.server.port=1883"
      - "traefik.tcp.routers.mosquitto.service=mosquitto-svc"

  jeedom:
    container_name: jeedom-server
    network_mode: host
    restart: always
    image: "jeedom/jeedom:latest"
    environment:
       APACHE_PORT: 9081
       SSH_PORT: 9022
       MODE_HOST: 1
    volumes:
      - ./www:/var/www
    depends_on:
      - mariadb
    devices:
      - "${RFXCOM}:/dev/ttyACM0"
      - "${ZIGATE}:/dev/ttyACM1"

  traefik:
    image: traefik:v2.1
    container_name: reverse_proxy
    command:
      - "--certificatesresolvers.mydnschallenge.acme.email=${ACME_EMAIL}"
    environment:
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
    labels:
      traefik.http.routers.jeedom.tls.domain[0].main: "${HOME_DOMAIN}"
      traefik.http.routers.jeedom.tls.domain[0].sans: "*.${HOME_DOMAIN}"
    ports:
      - "943:443"
      - "9080:8080"  # internal dashboard
      - "3307:3306"
      - "1884:1883"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik/dynamic_conf.toml:/etc/traefik/dynamic_conf.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
